apiVersion: apps/v1
kind: Deployment
metadata:
  name: azureshield-iam-blue
  labels:
    app: azureshield-iam
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: azureshield-iam
      version: blue
  template:
    metadata:
      labels:
        app: azureshield-iam
        version: blue
    spec:
      containers:
      - name: backend
        image: ${DOCKERHUB_USERNAME}/azureshield-iam-backend:${IMAGE_TAG}
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: azureshield-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: azureshield-secrets
              key: redis-url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: azureshield-secrets
              key: jwt-secret
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
      - name: frontend
        image: ${DOCKERHUB_USERNAME}/azureshield-iam-frontend:${IMAGE_TAG}
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://azureshield-iam-service:8000"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20 