apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azureshield-secrets
  namespace: azureshield-${ENVIRONMENT}
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${AKS_IDENTITY_ID}"
    keyvaultName: "${KEY_VAULT_NAME}"
    objects: |
      - objectName: postgres-admin-password
        objectType: secret
        objectVersion: ""
      - objectName: redis-key
        objectType: secret
        objectVersion: ""
      - objectName: jwt-secret
        objectType: secret
        objectVersion: ""
      - objectName: oauth-secrets
        objectType: secret
        objectVersion: ""
    tenantId: "${TENANT_ID}"
---
apiVersion: v1
kind: Pod
metadata:
  name: azureshield-secrets-pod
  namespace: azureshield-${ENVIRONMENT}
spec:
  containers:
    - name: azureshield-secrets
      image: mcr.microsoft.com/aks/secret-store-csi-driver-provider-azure:latest
      volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
  volumes:
    - name: secrets-store
      csi:
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: azureshield-secrets 