apiVersion: v1
kind: Service
metadata:
  name: azureshield-iam-service
spec:
  type: LoadBalancer
  ports:
  - name: backend
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: frontend
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: azureshield-iam
    version: blue 