groups:
  - name: azureshield_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High error rate detected
          description: "Error rate is above 10% for the last 5 minutes"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High latency detected
          description: "95th percentile latency is above 1 second"

      - alert: DatabaseConnectionIssues
        expr: up{job="azureshield_iam", instance=~".*db.*"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Database connection issues
          description: "Database connection is down"

      - alert: RedisConnectionIssues
        expr: up{job="azureshield_iam", instance=~".*redis.*"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Redis connection issues
          description: "Redis connection is down"

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes / process_virtual_memory_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High memory usage
          description: "Memory usage is above 80%" 